### PR TITLE
Hook into ContentObjectRenderer to extend getData

### PR DESCRIPTION
**Pull request by kitzberger**
Now you can access the frontendBase for the current base variant via TypoScript:

```
lib.frontendBase = TEXT
lib.frontendBase.data = site:frontendBase
```

### CODE REVIEW

**Comment by twoldanski** [comment]
Hi @kitzberger, could you provide site yaml with variants file you are using? (with redacted domains)

**Comment by kitzberger** [comment]
> Hi @kitzberger, could you provide site yaml with variants file you are using? (with redacted domains)

@twoldanski, sure thing. It's usually something like this here:

```
base: 'https://api.example.org/'
frontendBase: 'https://www.example.org/'
frontendFileApi: 'https://www.example.org/fileadmin/'
baseVariants:
  -
    base: 'https://api.example.org:8080/'
    frontendBase: 'https://www.example.org:3000/'
    frontendFileApi: 'https://www.example.org:3000/fileadmin/'
    condition: 'like(applicationContext, "Development*") || applicationContext == "Production/Docker"'
```

But as a workaround we've now added another (redundant) baseVariant for "Production":

```
base: 'https://api.example.org/'
frontendBase: 'https://www.example.org/'
frontendFileApi: 'https://www.example.org/fileadmin/'
baseVariants:
  -
    base: 'https://api.example.org/'
    frontendBase: 'https://www.example.org/'
    frontendFileApi: 'https://www.example.org/fileadmin/'
    condition: 'applicationContext == "Production"'
  -
    base: 'https://api.example.org:8080/'
    frontendBase: 'https://www.example.org:3000/'
    frontendFileApi: 'https://www.example.org:3000/fileadmin/'
    condition: 'like(applicationContext, "Development*") || applicationContext == "Production/Docker"'
```

**Comment by kitzberger** [comment]
@twoldanski, you're saying our workaround is the way it's supposed to be? At least for now?

**Comment by twoldanski** [comment]
@kitzberger yes, current way -> you should define each env as variant, but you workflow is also valid, this patch should fix it for you https://github.com/TYPO3-Headless/headless/pull/435, I think this PR should be closed, I think this hook is not necessary either way.

**Comment by kitzberger** [comment]
Still a valid new feature... I always like being able to read data via typoscript... And until now it's not possible to read those properties...

**Comment by lukaszuznanski** [comment]
@kitzberger could please add test so we can merge this?

**Pull request closed without merging**
