### PR TITLE
[FEATURE] Add flag to DatabaseQueryProcessor to render only one record

### PR DESCRIPTION
**Pull request by kitzberger**
In order for this meta data override to work we had to introduce a new flag `renderOnlyOne` to `DatabaseQueryProcessor`.

Maybe there's a better solution?

```
  lib.meta.stdWrap.override.cObject = JSON
  lib.meta.stdWrap.override.cObject {
    stdWrap.if.isTrue.data = GP:tx_news_pi1|news
    dataProcessing.10 = FriendsOfTYPO3\Headless\DataProcessing\DatabaseQueryProcessor
    dataProcessing.10 {
      table = tx_news_domain_model_news
      uidInList.data = GP:tx_news_pi1|news
      uidInList.intval = 1
      pidInList = 0
      max = 1
      as = records
      fields < lib.meta.fields
      fields {
        title = TEXT
        title.field = title
        subtitle = TEXT
        subtitle.field = teaser
        description = TEXT
        description.field = bodytext
      }

      renderOnlyOne = 1
    }
  }
```

| Before | After |
| -- | -- |
| Bildschirmfoto vom 2022-03-18 07-23-50 | Bildschirmfoto vom 2022-03-18 07-23-30 |

Related: #420

### CODE REVIEW

**Comment by lukaszuznanski** [comment]
Hi,

we have very similar functionality in FilesProcessor, could we unify naming? https://github.com/TYPO3-Headless/headless/blob/master/Classes/DataProcessing/FilesProcessor.php#L238

**Comment by kitzberger** [comment]
> Hi,
> 
> we have very similar functionality in FilesProcessor, could we unify naming? https://github.com/TYPO3-Headless/headless/blob/master/Classes/DataProcessing/FilesProcessor.php#L238

@lukaszuznanski , sure thing! Thanks for the input ;-) Done.

**Comment by lukaszuznanski** [comment]
@kitzberger 
You can also use RECORDS cObj here. In my projects I'm using RECORDS instead of fetching data using DatabaseQueryProcessor
```
    lib.page.fields.title = RECORDS
    lib.page.fields.title {
        dontCheckPid = 1
        tables = tx_news_domain_model_news
        source.data = GP:tx_news_pi1|news
        source.intval = 1
        conf.tx_news_domain_model_news = TEXT
        conf.tx_news_domain_model_news {
            field = title
            htmlSpecialChars = 1
        }
    }
```
but then, you need to do this per every single property, so your solution is cleaner.

**Comment by kitzberger** [comment]
> @kitzberger You can also use RECORDS cObj here. In my projects I'm using RECORDS instead of fetching data using DatabaseQueryProcessor
> but then, you need to do this per every single property, so your solution is cleaner.

@lukaszuznanski, yeah, that was my first try as well but then I realized that's 10 times more DB queries ;-/ Thanks for merging ;-)

**Review by lukaszuznanski — APPROVED** [review]

**Pull request merged**
