### PR TITLE
FilesProcessor: Added processed cropVariants to JSON output

### PR DESCRIPTION
**Pull request by svenpet90**
The FilesProcessor just outputs the URL to one given cropVariant (or "default") plus the crop-config array stored in $image['properties']['crop']. 
This data isn't all that useful for a frontend application though.

This PR adds a "cropVariants" Key to the processed image data, containing all rendered and processed cropVariants of a given File.

This way a frontend app can access the cropped images very easily.

Example Output:
Bildschirmfoto 2022-02-18 um 14 38 17

### CODE REVIEW

**Review by lukaszuznanski — CHANGES_REQUESTED** [review]
could you please update/fix tests so we can merge this?

**Comment by svenpet90** [comment]
@lukaszuznanski sure thing! Just fixed the failing tests and also added a check for an image having at least 2 cropVariants (the "default" + at least one other) to add the new "cropVariants" key. 

Otherwise we would just end up with the exact same information in die 'cropVariants' array.

---

I also thought about removing all keys in ['cropvariants]['variantName']['properties'] except for 'size' and 'dimensions', since all the other data is identical to the "main" image.

The only _downside_ or _inconvinience_ to this is that it would properbly make using the cropVariants Image a bit "harder" in the frontend since you would have to pull information from different places. (e.g. Image Title would always be in ['properties']['title'] while you would have to fetch the image url from ['cropVariants]['variantName']['publicUrl']

What do you think about this? :-)

**Comment by lukaszuznanski** [comment]
> @lukaszuznanski sure thing! Just fixed the failing tests and also added a check for an image having at least 2 cropVariants (the "default" + at least one other) to add the new "cropVariants" key.
> 
> Otherwise we would just end up with the exact same information in die 'cropVariants' array.
> 
> I also thought about removing all keys in ['cropvariants]['variantName']['properties'] except for 'size' and 'dimensions', since all the other data is identical to the "main" image.
> 
> The only _downside_ or _inconvinience_ to this is that it would properbly make using the cropVariants Image a bit "harder" in the frontend since you would have to pull information from different places. (e.g. Image Title would always be in ['properties']['title'] while you would have to fetch the image url from ['cropVariants]['variantName']['publicUrl']
> 
> What do you think about this? :-)

I think we can keep keys in properties for now.

**Review by lukaszuznanski — APPROVED** [review]

**Comment by svenpet90** [comment]
> I think we can keep keys in properties for now.
Alright 👍 
Thanks for merging 🎉  :)

**Pull request merged**
