### PR TITLE
[#122] renders all data that comes from dataProcessor

### LINKED ISSUE #122: dataProcessor returning empty array if no "as" conf value found in typoscript
Hi guys, i am struggling with dataProcessors in custom content elements and headless…
assuming a content element dataProcessing like following:
```
tt_content.borderelement.dataProcessing {
    1001 = Border\SitePackage\Processor\ContentElementsProcessor
}
```
and finding in extension code
`FriendsOfTYPO3\Headless\ContentObject\JsonContentObject`
on line 205-210 the code is searching for a “as” definition in conf, otherwise it will return an empty array… this is perhaps not the right behaviour as the data processor for the content element itself will fill the data array to my proper needs. is this a bug? (bearbeitet)

### PR DESCRIPTION
**Pull request by gordon81**
Resolves #122

### CODE REVIEW

**Comment by lukaszuznanski** [comment]
need to resolve merge conflict

**Comment by lukaszuznanski** [comment]
Looks fine so far, but we need to keep old behavior when we have "as" set.

**Comment by gordon81** [comment]
if "as" set it work or "as" as "key" 

JsonContentObject row 162 to  $dataProcessingData['value'] =$data[$value];

but this breaks Frontend

**Review by meincms — APPROVED** [review]

**Comment by lukaszuznanski** [comment]
I think this should be adapted to new JsonContentObject version. If you want to keep this functionality, please create new PR with your changes.

**Pull request closed without merging**
