### PR TITLE
[BUGFIX] Fix crash when link is not resolved properly

### PR DESCRIPTION
**Pull request by twoldanski**
Typolink method return empty string when it can not resolve link parameter

### CODE REVIEW

**Comment by tmotyl** [comment]
for version 12 we should use LinkFactory here, don't we?https://github.com/TYPO3/typo3/commit/4f7c4d1cc240071b38144e8f1d42cc62cdaedbe6
maybe add a todo in code or create an issue, what do you think @twoldanski ?

**Comment by tmotyl** [comment]
please also add a test case for this issue

**Comment by twoldanski** [comment]
@tmotyl yeah for branch 4.x / T3 v12 we should use LinkFactory, also this class needs some cleanup on 4.x branch
I added quick test for it in 3.x

**Comment by tmotyl** [comment]
Cool, thanks

**Review by lukaszuznanski — APPROVED** [review]

**Comment by lukaszuznanski** [comment]
https://github.com/TYPO3-Headless/headless/pull/525 - new issue for v12

**Pull request merged**
